In [ ]:
### Han Gong
### Assignment Blog: https://hannah-gong.github.io/biostat823-hw-projects-website/
### Repo: https://github.com/Hannah-GOng/biostat823-hw-projects-website

In [1]:
import pandas as pd
import chart_studio.plotly as py
import plotly.offline as po
import plotly.graph_objs as pg
import matplotlib.pyplot as plt
%matplotlib inline

import plotly.graph_objects as go

In [2]:
df = pd.read_csv('malaria_inc.csv')

In [3]:
df.head()

,Entity,Code,Year,"Incidence of malaria (per 1,000 population at risk) (per 1,000 population at risk)"
0,Afghanistan,AFG,2000,107.100000
1,Afghanistan,AFG,2005,46.500000
2,Afghanistan,AFG,2010,23.900000
3,Afghanistan,AFG,2015,23.600000
4,Algeria,DZA,2000,0.037746

### Interactive Visulization1: Years vs Number of Incident

In [5]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objects as go

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Dropdown(
        id="year", value = 2000, clearable = False,
        options=[
            {'label': x, 'value': x}
            for x in df['Year'].unique()
        ]),
    dcc.Graph(id = 'graph', figure = {})
])
    

@app.callback(
    Output("graph", "figure"), 
    [Input("year", "value")])
def display(year):
    df_year = df[df['Year'] == year]
    
    data = dict(type='choropleth', 
            locations = df_year['Code'], 
            z = df_year['Incidence of malaria (per 1,000 population at risk) (per 1,000 population at risk)'], 
            text = df_year['Entity'])
    
    layout = dict(title = 'Incidence of malaria (per 1,000 population at risk) (per 1,000 population at risk',
              geo = dict(projection = {'type':'robinson'},
                         showlakes = True, 
                         lakecolor = 'rgb(0,191,255)'))
    
    fig = go.Figure(data = [data], 
              layout = layout)

    return fig
    

app.run_server(debug=True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

### Interactive Visulization2: Age Distribution vs Number of Death in each country Over years

In [6]:
df2 = pd.read_csv('malaria_deaths_age.csv')
df_under5 = df2[df2['age_group'] == 'Under 5']

In [7]:
df_under5.head()

   Unnamed: 0       entity code  year age_group      deaths
0           1  Afghanistan  AFG  1990   Under 5  184.606435
1           2  Afghanistan  AFG  1991   Under 5  191.658193
2           3  Afghanistan  AFG  1992   Under 5  197.140197
3           4  Afghanistan  AFG  1993   Under 5  207.357753
4           5  Afghanistan  AFG  1994   Under 5  226.209363

In [11]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objects as go

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Dropdown(
        id="country", value = 'Afghanistan', clearable = False,
        options=[
            {'label': x, 'value': x}
            for x in df_under5['entity'].unique()
        ]),
    dcc.Graph(id = 'graph', figure = {})
])
    

@app.callback(
    Output("graph", "figure"), 
    [Input("country", "value")])

def display(country):
    df_country = df_under5[df_under5['entity'] == country]
    
    fig = go.Figure(data=go.Bar(x = df_country['year'],
                                y = df_country['deaths']))
    
    fig.update_layout(title_text='Death of age group under 5')

    return fig
    

app.run_server(debug=True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

### Interactive Visulization3: Years vs Number of Death per 100,000 people

In [12]:
df3 = pd.read_csv('malaria_deaths.csv')

In [13]:
df3.head()

,Entity,Code,Year,"Deaths - Malaria - Sex: Both - Age: Age-standardized (Rate) (per 100,000 people)"
0,Afghanistan,AFG,1990,6.802930
1,Afghanistan,AFG,1991,6.973494
2,Afghanistan,AFG,1992,6.989882
3,Afghanistan,AFG,1993,7.088983
4,Afghanistan,AFG,1994,7.392472

In [ ]:
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import plotly.graph_objects as go

app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Slider(
        id='year',
        min=df3['Year'].min(),
        max=df3['Year'].max(),
        value=df3['Year'].min(),
        marks={str(year): str(year) for year in df3['Year'].unique()},
        step=None
    ),
    dcc.Graph(id = 'graph', figure = {})
])
    

@app.callback(
    Output("graph", "figure"), 
    [Input("year", "value")])

def display(year):
    df_year = df3[df3['Year'] == year]
    
    data = dict(type='choropleth', 
            locations = df_year['Code'], 
            z = df_year['Deaths - Malaria - Sex: Both - Age: Age-standardized (Rate) (per 100,000 people)'], 
            text = df_year['Entity'])
    
    layout = dict(title = 'Deaths - Malaria - Sex: Both - Age: Age-standardized (Rate) (per 100,000 people)',
              geo = dict(projection = {'type':'robinson'},
                         showlakes = True, 
                         lakecolor = 'rgb(0,191,255)'))
    
    fig = go.Figure(data = [data], 
              layout = layout)

    return fig
    

app.run_server(debug=True, use_reloader=False)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on